### ISSUE TITLE
Null pointer exception in RootClassFinder

### ISSUE THREAD

**Issue by Gtomika** [Gtomika/tframework-test#7]
Stack trace:

```java
java.lang.NullPointerException: Cannot invoke "Object.equals(Object)" because the return value of "org.tframework.test.commons.TestConfig.rootClass()" is null
	at org.tframework.test.commons.utils.RootClassFinder.findRootClass(RootClassFinder.java:36)
	at org.tframework.test.commons.TestApplicationLauncher.launchTestApplicationInternal(TestApplicationLauncher.java:47)
	at org.tframework.test.commons.TestApplicationLauncher.launchTestApplication(TestApplicationLauncher.java:39)
	at org.tframework.test.junit5.TFrameworkExtension.beforeAll(TFrameworkExtension.java:163)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
```

Code that produced exception:

```java
@TFrameworkRootClass
public class CustomPreConstructedElementTest {

    private static final Object CUSTOM_PRE_CONSTRUCTED_ELEMENT = new Object();

    @RegisterExtension
    public static TFrameworkExtension tFrameworkExtension = TFrameworkExtension.isolatedTFrameworkTest()
            .preConstructedElements(Set.of(
                    PreConstructedElementData.from(CUSTOM_PRE_CONSTRUCTED_ELEMENT)
            ))
            .build()
            .toJunit5Extension();

    @Test
    public void shouldRegisterCustomPreConstructedElement(@InjectElement Object customPreConstructedElement) {
        assertSame(CUSTOM_PRE_CONSTRUCTED_ELEMENT, customPreConstructedElement);
    }
}
```

**Comment by Gtomika** [comment]
Can be fixed by adding ` .rootClass(CustomPreConstructedElementTest.class)` to the builder, but this should not be required. Selecting the root class should be done by the default builder `TFrameworkExtension.isolatedTFrameworkTest()`.
